// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package com.irisking.protobuf;

public interface FeatureBackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irisking.protobuf.FeatureBack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>optional uint32 appId = 3;</code>
   */
  int getAppId();

  /**
   * <code>optional uint32 orgId = 4;</code>
   */
  int getOrgId();

  /**
   * <code>optional .irisking.protobuf.IrisData data = 5;</code>
   */
  boolean hasData();
  /**
   * <code>optional .irisking.protobuf.IrisData data = 5;</code>
   */
  com.irisking.protobuf.IrisData getData();
  /**
   * <code>optional .irisking.protobuf.IrisData data = 5;</code>
   */
  com.irisking.protobuf.IrisDataOrBuilder getDataOrBuilder();
}
