// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package com.irisking.protobuf;

public interface IdenByImgBackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irisking.protobuf.IdenByImgBack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>optional uint32 appId = 3;</code>
   */
  int getAppId();

  /**
   * <code>optional uint32 orgId = 4;</code>
   */
  int getOrgId();

  /**
   * <code>optional string openId = 5;</code>
   */
  java.lang.String getOpenId();
  /**
   * <code>optional string openId = 5;</code>
   */
  com.google.protobuf.ByteString
      getOpenIdBytes();
}
