// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package com.irisking.protobuf;

/**
 * Protobuf type {@code irisking.protobuf.IdenByImgBack}
 *
 * <pre>
 *图像识别的应答
 * </pre>
 */
public  final class IdenByImgBack extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:irisking.protobuf.IdenByImgBack)
    IdenByImgBackOrBuilder {
  // Use IdenByImgBack.newBuilder() to construct.
  private IdenByImgBack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private IdenByImgBack() {
    code_ = 0;
    msg_ = "";
    appId_ = 0;
    orgId_ = 0;
    openId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private IdenByImgBack(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            code_ = input.readUInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          case 24: {

            appId_ = input.readUInt32();
            break;
          }
          case 32: {

            orgId_ = input.readUInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            openId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.irisking.protobuf.ProtoMsg.internal_static_irisking_protobuf_IdenByImgBack_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.irisking.protobuf.ProtoMsg.internal_static_irisking_protobuf_IdenByImgBack_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.irisking.protobuf.IdenByImgBack.class, com.irisking.protobuf.IdenByImgBack.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>optional uint32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int MSG_FIELD_NUMBER = 2;
  private volatile java.lang.Object msg_;
  /**
   * <code>optional string msg = 2;</code>
   */
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>optional string msg = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPID_FIELD_NUMBER = 3;
  private int appId_;
  /**
   * <code>optional uint32 appId = 3;</code>
   */
  public int getAppId() {
    return appId_;
  }

  public static final int ORGID_FIELD_NUMBER = 4;
  private int orgId_;
  /**
   * <code>optional uint32 orgId = 4;</code>
   */
  public int getOrgId() {
    return orgId_;
  }

  public static final int OPENID_FIELD_NUMBER = 5;
  private volatile java.lang.Object openId_;
  /**
   * <code>optional string openId = 5;</code>
   */
  public java.lang.String getOpenId() {
    java.lang.Object ref = openId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      openId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string openId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getOpenIdBytes() {
    java.lang.Object ref = openId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      openId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeUInt32(1, code_);
    }
    if (!getMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, msg_);
    }
    if (appId_ != 0) {
      output.writeUInt32(3, appId_);
    }
    if (orgId_ != 0) {
      output.writeUInt32(4, orgId_);
    }
    if (!getOpenIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, openId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, code_);
    }
    if (!getMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, msg_);
    }
    if (appId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, appId_);
    }
    if (orgId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, orgId_);
    }
    if (!getOpenIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, openId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.irisking.protobuf.IdenByImgBack)) {
      return super.equals(obj);
    }
    com.irisking.protobuf.IdenByImgBack other = (com.irisking.protobuf.IdenByImgBack) obj;

    boolean result = true;
    result = result && (getCode()
        == other.getCode());
    result = result && getMsg()
        .equals(other.getMsg());
    result = result && (getAppId()
        == other.getAppId());
    result = result && (getOrgId()
        == other.getOrgId());
    result = result && getOpenId()
        .equals(other.getOpenId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (37 * hash) + APPID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId();
    hash = (37 * hash) + ORGID_FIELD_NUMBER;
    hash = (53 * hash) + getOrgId();
    hash = (37 * hash) + OPENID_FIELD_NUMBER;
    hash = (53 * hash) + getOpenId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.irisking.protobuf.IdenByImgBack parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.irisking.protobuf.IdenByImgBack parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.irisking.protobuf.IdenByImgBack parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.irisking.protobuf.IdenByImgBack parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.irisking.protobuf.IdenByImgBack parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.irisking.protobuf.IdenByImgBack parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.irisking.protobuf.IdenByImgBack parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.irisking.protobuf.IdenByImgBack parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.irisking.protobuf.IdenByImgBack parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.irisking.protobuf.IdenByImgBack parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.irisking.protobuf.IdenByImgBack prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code irisking.protobuf.IdenByImgBack}
   *
   * <pre>
   *图像识别的应答
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:irisking.protobuf.IdenByImgBack)
      com.irisking.protobuf.IdenByImgBackOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.irisking.protobuf.ProtoMsg.internal_static_irisking_protobuf_IdenByImgBack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.irisking.protobuf.ProtoMsg.internal_static_irisking_protobuf_IdenByImgBack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.irisking.protobuf.IdenByImgBack.class, com.irisking.protobuf.IdenByImgBack.Builder.class);
    }

    // Construct using com.irisking.protobuf.IdenByImgBack.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      code_ = 0;

      msg_ = "";

      appId_ = 0;

      orgId_ = 0;

      openId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.irisking.protobuf.ProtoMsg.internal_static_irisking_protobuf_IdenByImgBack_descriptor;
    }

    public com.irisking.protobuf.IdenByImgBack getDefaultInstanceForType() {
      return com.irisking.protobuf.IdenByImgBack.getDefaultInstance();
    }

    public com.irisking.protobuf.IdenByImgBack build() {
      com.irisking.protobuf.IdenByImgBack result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.irisking.protobuf.IdenByImgBack buildPartial() {
      com.irisking.protobuf.IdenByImgBack result = new com.irisking.protobuf.IdenByImgBack(this);
      result.code_ = code_;
      result.msg_ = msg_;
      result.appId_ = appId_;
      result.orgId_ = orgId_;
      result.openId_ = openId_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.irisking.protobuf.IdenByImgBack) {
        return mergeFrom((com.irisking.protobuf.IdenByImgBack)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.irisking.protobuf.IdenByImgBack other) {
      if (other == com.irisking.protobuf.IdenByImgBack.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      if (other.getAppId() != 0) {
        setAppId(other.getAppId());
      }
      if (other.getOrgId() != 0) {
        setOrgId(other.getOrgId());
      }
      if (!other.getOpenId().isEmpty()) {
        openId_ = other.openId_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.irisking.protobuf.IdenByImgBack parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.irisking.protobuf.IdenByImgBack) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int code_ ;
    /**
     * <code>optional uint32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>optional uint32 code = 1;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <code>optional string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }

    private int appId_ ;
    /**
     * <code>optional uint32 appId = 3;</code>
     */
    public int getAppId() {
      return appId_;
    }
    /**
     * <code>optional uint32 appId = 3;</code>
     */
    public Builder setAppId(int value) {
      
      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 appId = 3;</code>
     */
    public Builder clearAppId() {
      
      appId_ = 0;
      onChanged();
      return this;
    }

    private int orgId_ ;
    /**
     * <code>optional uint32 orgId = 4;</code>
     */
    public int getOrgId() {
      return orgId_;
    }
    /**
     * <code>optional uint32 orgId = 4;</code>
     */
    public Builder setOrgId(int value) {
      
      orgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 orgId = 4;</code>
     */
    public Builder clearOrgId() {
      
      orgId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object openId_ = "";
    /**
     * <code>optional string openId = 5;</code>
     */
    public java.lang.String getOpenId() {
      java.lang.Object ref = openId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        openId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string openId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOpenIdBytes() {
      java.lang.Object ref = openId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        openId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string openId = 5;</code>
     */
    public Builder setOpenId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      openId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string openId = 5;</code>
     */
    public Builder clearOpenId() {
      
      openId_ = getDefaultInstance().getOpenId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string openId = 5;</code>
     */
    public Builder setOpenIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      openId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:irisking.protobuf.IdenByImgBack)
  }

  // @@protoc_insertion_point(class_scope:irisking.protobuf.IdenByImgBack)
  private static final com.irisking.protobuf.IdenByImgBack DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.irisking.protobuf.IdenByImgBack();
  }

  public static com.irisking.protobuf.IdenByImgBack getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IdenByImgBack>
      PARSER = new com.google.protobuf.AbstractParser<IdenByImgBack>() {
    public IdenByImgBack parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new IdenByImgBack(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<IdenByImgBack> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IdenByImgBack> getParserForType() {
    return PARSER;
  }

  public com.irisking.protobuf.IdenByImgBack getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

