// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: any.proto

package com.seeplant.protobuf;

public interface ByeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:seeplant.protobuf.Bye)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .seeplant.protobuf.MsgType msgType = 1;</code>
   */
  int getMsgTypeValue();
  /**
   * <code>optional .seeplant.protobuf.MsgType msgType = 1;</code>
   */
  com.seeplant.protobuf.MsgType getMsgType();

  /**
   * <code>optional string userType = 2;</code>
   */
  java.lang.String getUserType();
  /**
   * <code>optional string userType = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserTypeBytes();

  /**
   * <code>optional int64 uid = 3;</code>
   */
  long getUid();
}
