// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: any.proto

package com.seeplant.protobuf;

public interface LoginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:seeplant.protobuf.Login)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 msgType = 1;</code>
   */
  int getMsgType();

  /**
   * <code>optional string userType = 2;</code>
   */
  java.lang.String getUserType();
  /**
   * <code>optional string userType = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserTypeBytes();

  /**
   * <code>optional int64 uid = 3;</code>
   */
  long getUid();

  /**
   * <code>optional string userName = 4;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>optional string userName = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>optional string password = 5;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>optional string password = 5;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
