// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: any.proto

package com.seeplant.protobuf;

/**
 * Protobuf enum {@code seeplant.protobuf.MsgType}
 */
public enum MsgType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LOGIN = 0;</code>
   */
  LOGIN(0, 0),
  /**
   * <code>BYE = 1;</code>
   */
  BYE(1, 1),
  /**
   * <code>PING = 2;</code>
   */
  PING(2, 2),
  UNRECOGNIZED(-1, -1),
  ;

  /**
   * <code>LOGIN = 0;</code>
   */
  public static final int LOGIN_VALUE = 0;
  /**
   * <code>BYE = 1;</code>
   */
  public static final int BYE_VALUE = 1;
  /**
   * <code>PING = 2;</code>
   */
  public static final int PING_VALUE = 2;


  public final int getNumber() {
    if (index == -1) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  public static MsgType valueOf(int value) {
    switch (value) {
      case 0: return LOGIN;
      case 1: return BYE;
      case 2: return PING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MsgType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
          public MsgType findValueByNumber(int number) {
            return MsgType.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.seeplant.protobuf.ProtoMsg.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final MsgType[] VALUES = values();

  public static MsgType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private MsgType(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:seeplant.protobuf.MsgType)
}

