// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: any.proto

package com.seeplant.protobuf;

/**
 * Protobuf type {@code seeplant.protobuf.Protocol}
 *
 * <pre>
 *新定义接口的时候，先新建立一个message，然后在Protocol中添加这个message的实例
 * </pre>
 */
public  final class Protocol extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:seeplant.protobuf.Protocol)
    ProtocolOrBuilder {
  // Use Protocol.newBuilder() to construct.
  private Protocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Protocol() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Protocol(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();

    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.seeplant.protobuf.Login.Builder subBuilder = null;
            if (login_ != null) {
              subBuilder = login_.toBuilder();
            }
            login_ = input.readMessage(com.seeplant.protobuf.Login.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(login_);
              login_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.seeplant.protobuf.Bye.Builder subBuilder = null;
            if (bye_ != null) {
              subBuilder = bye_.toBuilder();
            }
            bye_ = input.readMessage(com.seeplant.protobuf.Bye.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bye_);
              bye_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.seeplant.protobuf.Ping.Builder subBuilder = null;
            if (ping_ != null) {
              subBuilder = ping_.toBuilder();
            }
            ping_ = input.readMessage(com.seeplant.protobuf.Ping.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ping_);
              ping_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.seeplant.protobuf.ProtoMsg.internal_static_seeplant_protobuf_Protocol_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.seeplant.protobuf.ProtoMsg.internal_static_seeplant_protobuf_Protocol_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.seeplant.protobuf.Protocol.class, com.seeplant.protobuf.Protocol.Builder.class);
  }

  public static final int LOGIN_FIELD_NUMBER = 1;
  private com.seeplant.protobuf.Login login_;
  /**
   * <code>optional .seeplant.protobuf.Login login = 1;</code>
   */
  public boolean hasLogin() {
    return login_ != null;
  }
  /**
   * <code>optional .seeplant.protobuf.Login login = 1;</code>
   */
  public com.seeplant.protobuf.Login getLogin() {
    return login_ == null ? com.seeplant.protobuf.Login.getDefaultInstance() : login_;
  }
  /**
   * <code>optional .seeplant.protobuf.Login login = 1;</code>
   */
  public com.seeplant.protobuf.LoginOrBuilder getLoginOrBuilder() {
    return getLogin();
  }

  public static final int BYE_FIELD_NUMBER = 3;
  private com.seeplant.protobuf.Bye bye_;
  /**
   * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
   */
  public boolean hasBye() {
    return bye_ != null;
  }
  /**
   * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
   */
  public com.seeplant.protobuf.Bye getBye() {
    return bye_ == null ? com.seeplant.protobuf.Bye.getDefaultInstance() : bye_;
  }
  /**
   * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
   */
  public com.seeplant.protobuf.ByeOrBuilder getByeOrBuilder() {
    return getBye();
  }

  public static final int PING_FIELD_NUMBER = 4;
  private com.seeplant.protobuf.Ping ping_;
  /**
   * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
   */
  public boolean hasPing() {
    return ping_ != null;
  }
  /**
   * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
   */
  public com.seeplant.protobuf.Ping getPing() {
    return ping_ == null ? com.seeplant.protobuf.Ping.getDefaultInstance() : ping_;
  }
  /**
   * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
   */
  public com.seeplant.protobuf.PingOrBuilder getPingOrBuilder() {
    return getPing();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (login_ != null) {
      output.writeMessage(1, getLogin());
    }
    if (bye_ != null) {
      output.writeMessage(3, getBye());
    }
    if (ping_ != null) {
      output.writeMessage(4, getPing());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (login_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLogin());
    }
    if (bye_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBye());
    }
    if (ping_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPing());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.seeplant.protobuf.Protocol)) {
      return super.equals(obj);
    }
    com.seeplant.protobuf.Protocol other = (com.seeplant.protobuf.Protocol) obj;

    boolean result = true;
    result = result && (hasLogin() == other.hasLogin());
    if (hasLogin()) {
      result = result && getLogin()
          .equals(other.getLogin());
    }
    result = result && (hasBye() == other.hasBye());
    if (hasBye()) {
      result = result && getBye()
          .equals(other.getBye());
    }
    result = result && (hasPing() == other.hasPing());
    if (hasPing()) {
      result = result && getPing()
          .equals(other.getPing());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasLogin()) {
      hash = (37 * hash) + LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getLogin().hashCode();
    }
    if (hasBye()) {
      hash = (37 * hash) + BYE_FIELD_NUMBER;
      hash = (53 * hash) + getBye().hashCode();
    }
    if (hasPing()) {
      hash = (37 * hash) + PING_FIELD_NUMBER;
      hash = (53 * hash) + getPing().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.seeplant.protobuf.Protocol parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seeplant.protobuf.Protocol parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seeplant.protobuf.Protocol parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seeplant.protobuf.Protocol parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seeplant.protobuf.Protocol parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.seeplant.protobuf.Protocol parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.seeplant.protobuf.Protocol parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.seeplant.protobuf.Protocol parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.seeplant.protobuf.Protocol parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.seeplant.protobuf.Protocol parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.seeplant.protobuf.Protocol prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code seeplant.protobuf.Protocol}
   *
   * <pre>
   *新定义接口的时候，先新建立一个message，然后在Protocol中添加这个message的实例
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:seeplant.protobuf.Protocol)
      com.seeplant.protobuf.ProtocolOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeplant.protobuf.ProtoMsg.internal_static_seeplant_protobuf_Protocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeplant.protobuf.ProtoMsg.internal_static_seeplant_protobuf_Protocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeplant.protobuf.Protocol.class, com.seeplant.protobuf.Protocol.Builder.class);
    }

    // Construct using com.seeplant.protobuf.Protocol.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (loginBuilder_ == null) {
        login_ = null;
      } else {
        login_ = null;
        loginBuilder_ = null;
      }
      if (byeBuilder_ == null) {
        bye_ = null;
      } else {
        bye_ = null;
        byeBuilder_ = null;
      }
      if (pingBuilder_ == null) {
        ping_ = null;
      } else {
        ping_ = null;
        pingBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.seeplant.protobuf.ProtoMsg.internal_static_seeplant_protobuf_Protocol_descriptor;
    }

    public com.seeplant.protobuf.Protocol getDefaultInstanceForType() {
      return com.seeplant.protobuf.Protocol.getDefaultInstance();
    }

    public com.seeplant.protobuf.Protocol build() {
      com.seeplant.protobuf.Protocol result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.seeplant.protobuf.Protocol buildPartial() {
      com.seeplant.protobuf.Protocol result = new com.seeplant.protobuf.Protocol(this);
      if (loginBuilder_ == null) {
        result.login_ = login_;
      } else {
        result.login_ = loginBuilder_.build();
      }
      if (byeBuilder_ == null) {
        result.bye_ = bye_;
      } else {
        result.bye_ = byeBuilder_.build();
      }
      if (pingBuilder_ == null) {
        result.ping_ = ping_;
      } else {
        result.ping_ = pingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.seeplant.protobuf.Protocol) {
        return mergeFrom((com.seeplant.protobuf.Protocol)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.seeplant.protobuf.Protocol other) {
      if (other == com.seeplant.protobuf.Protocol.getDefaultInstance()) return this;
      if (other.hasLogin()) {
        mergeLogin(other.getLogin());
      }
      if (other.hasBye()) {
        mergeBye(other.getBye());
      }
      if (other.hasPing()) {
        mergePing(other.getPing());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.seeplant.protobuf.Protocol parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.seeplant.protobuf.Protocol) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.seeplant.protobuf.Login login_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.seeplant.protobuf.Login, com.seeplant.protobuf.Login.Builder, com.seeplant.protobuf.LoginOrBuilder> loginBuilder_;
    /**
     * <code>optional .seeplant.protobuf.Login login = 1;</code>
     */
    public boolean hasLogin() {
      return loginBuilder_ != null || login_ != null;
    }
    /**
     * <code>optional .seeplant.protobuf.Login login = 1;</code>
     */
    public com.seeplant.protobuf.Login getLogin() {
      if (loginBuilder_ == null) {
        return login_ == null ? com.seeplant.protobuf.Login.getDefaultInstance() : login_;
      } else {
        return loginBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .seeplant.protobuf.Login login = 1;</code>
     */
    public Builder setLogin(com.seeplant.protobuf.Login value) {
      if (loginBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        login_ = value;
        onChanged();
      } else {
        loginBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Login login = 1;</code>
     */
    public Builder setLogin(
        com.seeplant.protobuf.Login.Builder builderForValue) {
      if (loginBuilder_ == null) {
        login_ = builderForValue.build();
        onChanged();
      } else {
        loginBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Login login = 1;</code>
     */
    public Builder mergeLogin(com.seeplant.protobuf.Login value) {
      if (loginBuilder_ == null) {
        if (login_ != null) {
          login_ =
            com.seeplant.protobuf.Login.newBuilder(login_).mergeFrom(value).buildPartial();
        } else {
          login_ = value;
        }
        onChanged();
      } else {
        loginBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Login login = 1;</code>
     */
    public Builder clearLogin() {
      if (loginBuilder_ == null) {
        login_ = null;
        onChanged();
      } else {
        login_ = null;
        loginBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Login login = 1;</code>
     */
    public com.seeplant.protobuf.Login.Builder getLoginBuilder() {
      
      onChanged();
      return getLoginFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .seeplant.protobuf.Login login = 1;</code>
     */
    public com.seeplant.protobuf.LoginOrBuilder getLoginOrBuilder() {
      if (loginBuilder_ != null) {
        return loginBuilder_.getMessageOrBuilder();
      } else {
        return login_ == null ?
            com.seeplant.protobuf.Login.getDefaultInstance() : login_;
      }
    }
    /**
     * <code>optional .seeplant.protobuf.Login login = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.seeplant.protobuf.Login, com.seeplant.protobuf.Login.Builder, com.seeplant.protobuf.LoginOrBuilder> 
        getLoginFieldBuilder() {
      if (loginBuilder_ == null) {
        loginBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.seeplant.protobuf.Login, com.seeplant.protobuf.Login.Builder, com.seeplant.protobuf.LoginOrBuilder>(
                getLogin(),
                getParentForChildren(),
                isClean());
        login_ = null;
      }
      return loginBuilder_;
    }

    private com.seeplant.protobuf.Bye bye_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.seeplant.protobuf.Bye, com.seeplant.protobuf.Bye.Builder, com.seeplant.protobuf.ByeOrBuilder> byeBuilder_;
    /**
     * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
     */
    public boolean hasBye() {
      return byeBuilder_ != null || bye_ != null;
    }
    /**
     * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
     */
    public com.seeplant.protobuf.Bye getBye() {
      if (byeBuilder_ == null) {
        return bye_ == null ? com.seeplant.protobuf.Bye.getDefaultInstance() : bye_;
      } else {
        return byeBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
     */
    public Builder setBye(com.seeplant.protobuf.Bye value) {
      if (byeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bye_ = value;
        onChanged();
      } else {
        byeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
     */
    public Builder setBye(
        com.seeplant.protobuf.Bye.Builder builderForValue) {
      if (byeBuilder_ == null) {
        bye_ = builderForValue.build();
        onChanged();
      } else {
        byeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
     */
    public Builder mergeBye(com.seeplant.protobuf.Bye value) {
      if (byeBuilder_ == null) {
        if (bye_ != null) {
          bye_ =
            com.seeplant.protobuf.Bye.newBuilder(bye_).mergeFrom(value).buildPartial();
        } else {
          bye_ = value;
        }
        onChanged();
      } else {
        byeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
     */
    public Builder clearBye() {
      if (byeBuilder_ == null) {
        bye_ = null;
        onChanged();
      } else {
        bye_ = null;
        byeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
     */
    public com.seeplant.protobuf.Bye.Builder getByeBuilder() {
      
      onChanged();
      return getByeFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
     */
    public com.seeplant.protobuf.ByeOrBuilder getByeOrBuilder() {
      if (byeBuilder_ != null) {
        return byeBuilder_.getMessageOrBuilder();
      } else {
        return bye_ == null ?
            com.seeplant.protobuf.Bye.getDefaultInstance() : bye_;
      }
    }
    /**
     * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.seeplant.protobuf.Bye, com.seeplant.protobuf.Bye.Builder, com.seeplant.protobuf.ByeOrBuilder> 
        getByeFieldBuilder() {
      if (byeBuilder_ == null) {
        byeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.seeplant.protobuf.Bye, com.seeplant.protobuf.Bye.Builder, com.seeplant.protobuf.ByeOrBuilder>(
                getBye(),
                getParentForChildren(),
                isClean());
        bye_ = null;
      }
      return byeBuilder_;
    }

    private com.seeplant.protobuf.Ping ping_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.seeplant.protobuf.Ping, com.seeplant.protobuf.Ping.Builder, com.seeplant.protobuf.PingOrBuilder> pingBuilder_;
    /**
     * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
     */
    public boolean hasPing() {
      return pingBuilder_ != null || ping_ != null;
    }
    /**
     * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
     */
    public com.seeplant.protobuf.Ping getPing() {
      if (pingBuilder_ == null) {
        return ping_ == null ? com.seeplant.protobuf.Ping.getDefaultInstance() : ping_;
      } else {
        return pingBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
     */
    public Builder setPing(com.seeplant.protobuf.Ping value) {
      if (pingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ping_ = value;
        onChanged();
      } else {
        pingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
     */
    public Builder setPing(
        com.seeplant.protobuf.Ping.Builder builderForValue) {
      if (pingBuilder_ == null) {
        ping_ = builderForValue.build();
        onChanged();
      } else {
        pingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
     */
    public Builder mergePing(com.seeplant.protobuf.Ping value) {
      if (pingBuilder_ == null) {
        if (ping_ != null) {
          ping_ =
            com.seeplant.protobuf.Ping.newBuilder(ping_).mergeFrom(value).buildPartial();
        } else {
          ping_ = value;
        }
        onChanged();
      } else {
        pingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
     */
    public Builder clearPing() {
      if (pingBuilder_ == null) {
        ping_ = null;
        onChanged();
      } else {
        ping_ = null;
        pingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
     */
    public com.seeplant.protobuf.Ping.Builder getPingBuilder() {
      
      onChanged();
      return getPingFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
     */
    public com.seeplant.protobuf.PingOrBuilder getPingOrBuilder() {
      if (pingBuilder_ != null) {
        return pingBuilder_.getMessageOrBuilder();
      } else {
        return ping_ == null ?
            com.seeplant.protobuf.Ping.getDefaultInstance() : ping_;
      }
    }
    /**
     * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.seeplant.protobuf.Ping, com.seeplant.protobuf.Ping.Builder, com.seeplant.protobuf.PingOrBuilder> 
        getPingFieldBuilder() {
      if (pingBuilder_ == null) {
        pingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.seeplant.protobuf.Ping, com.seeplant.protobuf.Ping.Builder, com.seeplant.protobuf.PingOrBuilder>(
                getPing(),
                getParentForChildren(),
                isClean());
        ping_ = null;
      }
      return pingBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:seeplant.protobuf.Protocol)
  }

  // @@protoc_insertion_point(class_scope:seeplant.protobuf.Protocol)
  private static final com.seeplant.protobuf.Protocol DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.seeplant.protobuf.Protocol();
  }

  public static com.seeplant.protobuf.Protocol getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Protocol>
      PARSER = new com.google.protobuf.AbstractParser<Protocol>() {
    public Protocol parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new Protocol(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<Protocol> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Protocol> getParserForType() {
    return PARSER;
  }

  public com.seeplant.protobuf.Protocol getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

