// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: any.proto

package com.seeplant.protobuf;

public final class ProtoMsg {
  private ProtoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_seeplant_protobuf_Protocol_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_seeplant_protobuf_Protocol_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_seeplant_protobuf_Login_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_seeplant_protobuf_Login_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_seeplant_protobuf_Bye_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_seeplant_protobuf_Bye_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_seeplant_protobuf_Ping_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_seeplant_protobuf_Ping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tany.proto\022\021seeplant.protobuf\"\177\n\010Protoc" +
      "ol\022\'\n\005login\030\001 \001(\0132\030.seeplant.protobuf.Lo" +
      "gin\022#\n\003bye\030\003 \001(\0132\026.seeplant.protobuf.Bye" +
      "\022%\n\004ping\030\004 \001(\0132\027.seeplant.protobuf.Ping\"" +
      "[\n\005Login\022\017\n\007msgType\030\001 \001(\r\022\020\n\010userType\030\002 " +
      "\001(\t\022\013\n\003uid\030\003 \001(\003\022\020\n\010userName\030\004 \001(\t\022\020\n\010pa" +
      "ssword\030\005 \001(\t\"Q\n\003Bye\022+\n\007msgType\030\001 \001(\0162\032.s" +
      "eeplant.protobuf.MsgType\022\020\n\010userType\030\002 \001" +
      "(\t\022\013\n\003uid\030\003 \001(\003\"R\n\004Ping\022+\n\007msgType\030\001 \001(\016" +
      "2\032.seeplant.protobuf.MsgType\022\020\n\010userType",
      "\030\002 \001(\t\022\013\n\003uid\030\003 \001(\003*\'\n\007MsgType\022\t\n\005LOGIN\020" +
      "\000\022\007\n\003BYE\020\001\022\010\n\004PING\020\002BM\n\025com.seeplant.pro" +
      "tobufB\010ProtoMsgP\001\240\001\001\242\002\003GPB\252\002\036Google.Prot" +
      "obuf.WellKnownTypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_seeplant_protobuf_Protocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_seeplant_protobuf_Protocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_seeplant_protobuf_Protocol_descriptor,
        new java.lang.String[] { "Login", "Bye", "Ping", });
    internal_static_seeplant_protobuf_Login_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_seeplant_protobuf_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_seeplant_protobuf_Login_descriptor,
        new java.lang.String[] { "MsgType", "UserType", "Uid", "UserName", "Password", });
    internal_static_seeplant_protobuf_Bye_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_seeplant_protobuf_Bye_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_seeplant_protobuf_Bye_descriptor,
        new java.lang.String[] { "MsgType", "UserType", "Uid", });
    internal_static_seeplant_protobuf_Ping_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_seeplant_protobuf_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_seeplant_protobuf_Ping_descriptor,
        new java.lang.String[] { "MsgType", "UserType", "Uid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
