// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: any.proto

package com.seeplant.protobuf;

public interface ProtocolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:seeplant.protobuf.Protocol)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .seeplant.protobuf.Login login = 1;</code>
   */
  boolean hasLogin();
  /**
   * <code>optional .seeplant.protobuf.Login login = 1;</code>
   */
  com.seeplant.protobuf.Login getLogin();
  /**
   * <code>optional .seeplant.protobuf.Login login = 1;</code>
   */
  com.seeplant.protobuf.LoginOrBuilder getLoginOrBuilder();

  /**
   * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
   */
  boolean hasBye();
  /**
   * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
   */
  com.seeplant.protobuf.Bye getBye();
  /**
   * <code>optional .seeplant.protobuf.Bye bye = 3;</code>
   */
  com.seeplant.protobuf.ByeOrBuilder getByeOrBuilder();

  /**
   * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
   */
  boolean hasPing();
  /**
   * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
   */
  com.seeplant.protobuf.Ping getPing();
  /**
   * <code>optional .seeplant.protobuf.Ping ping = 4;</code>
   */
  com.seeplant.protobuf.PingOrBuilder getPingOrBuilder();
}
