// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package com.irisking.protobuf;

public interface IdenByImgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irisking.protobuf.IdenByImg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 appId = 1;</code>
   */
  int getAppId();

  /**
   * <code>optional uint32 orgId = 2;</code>
   */
  int getOrgId();

  /**
   * <code>optional .irisking.protobuf.IrisData data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>optional .irisking.protobuf.IrisData data = 3;</code>
   */
  com.irisking.protobuf.IrisData getData();
  /**
   * <code>optional .irisking.protobuf.IrisData data = 3;</code>
   */
  com.irisking.protobuf.IrisDataOrBuilder getDataOrBuilder();
}
