// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package com.irisking.protobuf;

public interface IrisDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irisking.protobuf.IrisData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 imgHight = 1;</code>
   */
  int getImgHight();

  /**
   * <code>optional uint32 imgWidth = 2;</code>
   */
  int getImgWidth();

  /**
   * <code>optional uint32 imgType = 3;</code>
   */
  int getImgType();

  /**
   * <code>optional uint32 irisRow = 4;</code>
   */
  int getIrisRow();

  /**
   * <code>optional uint32 irisCol = 5;</code>
   */
  int getIrisCol();

  /**
   * <code>optional uint32 irisRadius = 6;</code>
   */
  int getIrisRadius();

  /**
   * <code>optional uint32 focusScore = 7;</code>
   */
  int getFocusScore();

  /**
   * <code>optional uint32 percentVisible = 8;</code>
   */
  int getPercentVisible();

  /**
   * <code>optional uint32 saturation = 9;</code>
   */
  int getSaturation();

  /**
   * <code>optional uint32 interlaceValue = 10;</code>
   */
  int getInterlaceValue();

  /**
   * <code>optional uint32 qualityScore = 11;</code>
   */
  int getQualityScore();

  /**
   * <code>optional uint32 jpegImSize = 12;</code>
   */
  int getJpegImSize();

  /**
   * <code>optional bytes imgData = 13;</code>
   */
  com.google.protobuf.ByteString getImgData();

  /**
   * <code>optional bytes unknowInfo = 14;</code>
   */
  com.google.protobuf.ByteString getUnknowInfo();

  /**
   * <code>optional bytes irisEnrTemplate = 15;</code>
   */
  com.google.protobuf.ByteString getIrisEnrTemplate();

  /**
   * <code>optional bytes irisRecTemplate = 16;</code>
   */
  com.google.protobuf.ByteString getIrisRecTemplate();
}
