// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package com.irisking.protobuf;

public final class ProtoMsg {
  private ProtoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irisking_protobuf_FeatureExtract_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irisking_protobuf_FeatureExtract_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irisking_protobuf_FeatureBack_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irisking_protobuf_FeatureBack_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irisking_protobuf_IdenByImg_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irisking_protobuf_IdenByImg_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irisking_protobuf_IdenByImgBack_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irisking_protobuf_IdenByImgBack_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irisking_protobuf_IrisData_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irisking_protobuf_IrisData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\niris.proto\022\021irisking.protobuf\"Y\n\016Featu" +
      "reExtract\022\r\n\005appId\030\001 \001(\r\022\r\n\005orgId\030\002 \001(\r\022" +
      ")\n\004data\030\003 \001(\0132\033.irisking.protobuf.IrisDa" +
      "ta\"q\n\013FeatureBack\022\014\n\004code\030\001 \001(\r\022\013\n\003msg\030\002" +
      " \001(\t\022\r\n\005appId\030\003 \001(\r\022\r\n\005orgId\030\004 \001(\r\022)\n\004da" +
      "ta\030\005 \001(\0132\033.irisking.protobuf.IrisData\"T\n" +
      "\tIdenByImg\022\r\n\005appId\030\001 \001(\r\022\r\n\005orgId\030\002 \001(\r" +
      "\022)\n\004data\030\003 \001(\0132\033.irisking.protobuf.IrisD" +
      "ata\"X\n\rIdenByImgBack\022\014\n\004code\030\001 \001(\r\022\013\n\003ms" +
      "g\030\002 \001(\t\022\r\n\005appId\030\003 \001(\r\022\r\n\005orgId\030\004 \001(\r\022\016\n",
      "\006openId\030\005 \001(\t\"\316\002\n\010IrisData\022\020\n\010imgHight\030\001" +
      " \001(\r\022\020\n\010imgWidth\030\002 \001(\r\022\017\n\007imgType\030\003 \001(\r\022" +
      "\017\n\007irisRow\030\004 \001(\r\022\017\n\007irisCol\030\005 \001(\r\022\022\n\niri" +
      "sRadius\030\006 \001(\r\022\022\n\nfocusScore\030\007 \001(\r\022\026\n\016per" +
      "centVisible\030\010 \001(\r\022\022\n\nsaturation\030\t \001(\r\022\026\n" +
      "\016interlaceValue\030\n \001(\r\022\024\n\014qualityScore\030\013 " +
      "\001(\r\022\022\n\njpegImSize\030\014 \001(\r\022\017\n\007imgData\030\r \001(\014" +
      "\022\022\n\nunknowInfo\030\016 \001(\014\022\027\n\017irisEnrTemplate\030" +
      "\017 \001(\014\022\027\n\017irisRecTemplate\030\020 \001(\014BM\n\025com.ir" +
      "isking.protobufB\010ProtoMsgP\001\240\001\001\242\002\003GPB\252\002\036G",
      "oogle.Protobuf.WellKnownTypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_irisking_protobuf_FeatureExtract_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_irisking_protobuf_FeatureExtract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irisking_protobuf_FeatureExtract_descriptor,
        new java.lang.String[] { "AppId", "OrgId", "Data", });
    internal_static_irisking_protobuf_FeatureBack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_irisking_protobuf_FeatureBack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irisking_protobuf_FeatureBack_descriptor,
        new java.lang.String[] { "Code", "Msg", "AppId", "OrgId", "Data", });
    internal_static_irisking_protobuf_IdenByImg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_irisking_protobuf_IdenByImg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irisking_protobuf_IdenByImg_descriptor,
        new java.lang.String[] { "AppId", "OrgId", "Data", });
    internal_static_irisking_protobuf_IdenByImgBack_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_irisking_protobuf_IdenByImgBack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irisking_protobuf_IdenByImgBack_descriptor,
        new java.lang.String[] { "Code", "Msg", "AppId", "OrgId", "OpenId", });
    internal_static_irisking_protobuf_IrisData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_irisking_protobuf_IrisData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irisking_protobuf_IrisData_descriptor,
        new java.lang.String[] { "ImgHight", "ImgWidth", "ImgType", "IrisRow", "IrisCol", "IrisRadius", "FocusScore", "PercentVisible", "Saturation", "InterlaceValue", "QualityScore", "JpegImSize", "ImgData", "UnknowInfo", "IrisEnrTemplate", "IrisRecTemplate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
